backend:
  name: github
  repo: HigorMoroni/higormoroni.github.io
  branch: master
  auth_type: oauth
  client_id: Ov23lizEMcXKZTgY3wA3

media_folder: public/images
public_folder: /images

collections:
  - name: "portfolio"
    label: "Portfolio"
    files:
      - label: "Dados do Portfolio"
        name: "portfolio"
        file: "public/data/portfolio.json"
        fields:
          - label: "Informações Pessoais"
            name: "personal"
            widget: "object"
            fields:
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "Cargo", name: "title", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Telefone", name: "phone", widget: "string"}
              - {label: "LinkedIn", name: "linkedin", widget: "string"}
              - {label: "GitHub", name: "github", widget: "string"}
              - {label: "Bio", name: "bio", widget: "text"}
              
          - label: "Projetos"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
              - {label: "URL", name: "url", widget: "string", required: false}
              - {label: "Repositório", name: "repo", widget: "string", required: false}
              - {label: "Imagem", name: "image", widget: "image", required: false}
              - label: "Tecnologias"
                name: "technologies"
                widget: "list"
                field: {label: "Tecnologia", name: "tech", widget: "string"}
              - {label: "Destaque", name: "featured", widget: "boolean", default: false}
              
          - label: "Skills"
            name: "skills"
            widget: "object"
            fields:
              - label: "Frontend"
                name: "frontend"
                widget: "list"
                field: {label: "Skill", name: "skill", widget: "string"}
              - label: "Backend"
                name: "backend"
                widget: "list"
                field: {label: "Skill", name: "skill", widget: "string"}
              - label: "Ferramentas"
                name: "tools"
                widget: "list"
                field: {label: "Tool", name: "tool", widget: "string"}
                
          - label: "Experiência"
            name: "experience"
            widget: "list"
            fields:
              - {label: "Empresa", name: "company", widget: "string"}
              - {label: "Cargo", name: "position", widget: "string"}
              - {label: "Período", name: "period", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
              
          - label: "Educação"
            name: "education"
            widget: "list"
            fields:
              - {label: "Instituição", name: "institution", widget: "string"}
              - {label: "Curso", name: "course", widget: "string"}
              - {label: "Período", name: "period", widget: "string"}